[package]
name = "mdb-async"
version = "0.1.0"
edition = "2021"
licence = ""
[dependencies]
defmt = "0.3.10"
embassy-time = "0.4.0"
embedded-io-async = "0.6.1"
enumn = "0.1.14"
fixedstr = { version = "0.5.8", features = ["serde", "no-alloc"] }
